#stage 1: Build
FROM maven:3.9.12-amazoncorretto-21 AS build
WORKDIR /app

# cache dependencies
COPY pom.xml .
RUN mvn dependency:go-offline -B

#TO compile the service into a jar excecutable file
COPY src ./src
RUN mvn clean package -DskipTests

#Stage 2: Runtime
FROM amazoncorretto:21
WORKDIR /app

#Copy the jar
COPY --from=build /app/target/*.jar app.jar

#Expose the port
EXPOSE 8083

ENTRYPOINT ["java", "-jar", "app.jar"]