#spring.config.import=optional:file:application-env.properties[.properties]
spring.config.import=optional:file:D:/springBoot/apigateway/apigateway/application-env.properties

spring.application.name=api-gateway
server.port=8080

logging.level.org.springframework.cloud.gateway=TRACE

spring.security.user.name=disabled
spring.security.user.password=disabled

#Jwt Config
jwt.secret=${JWT_SECRETE}

#EUREKA Discover
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/


# Actuator Config, Health Monitoring
management.endpoints.web.exposure.include=*

